@local =http://localhost:3000
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWFjZmQ3MjFjZjNkOGI1OGFmNWVkZDkiLCJiaXoiOnRydWUsImlhdCI6MTcwNTgzNjA5Nn0.CJBiPMnleWPIGhP1negNduJHmnUZHqre8s69glkwBwo
### REGISTE
POST {{local}}/api/users
Content-Type: application/json

{
    "name": "loren", 
    "email": "loren@yyy.com", 
    "password": "Aa123456",
    "biz": true
}


### login
POST {{local}}/api/auth
Content-Type: application/json

{
    "email":"loren@yyy.com",
    "password":"Aa123456"
}

###
GET {{local}}/api/users/me
x-auth-token: {{token}}


### Card
POST {{local}}/api/cards
Content-Type: application/json
x-auth-token: {{token}}

{
    "bizName":"dsadad",
    "bizDescription":"sdadad",
    "bizAddress":"bizAddress",
    "bizPhone":"023131313"
}
